# Generated by Django 4.2.8 on 2024-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UType',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=150),
        ),
    ]
