# Generated by Django 4.2.8 on 2024-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_user_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UEmail',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
