# Generated by Django 4.2.9 on 2024-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user_uemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
