# Generated by Django 4.2.9 on 2024-01-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_user_uemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
