# Generated by Django 4.2.9 on 2024-01-15 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_priority_alter_task_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 1, 15)),
        ),
    ]
