# Generated by Django 4.2.9 on 2024-01-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ListID',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
